WIP Siitbx 463 s2 evolution 8x
senbox-org/snap-engine pull request #306
Opened 2021-11-09 19:41 UTC by Florian1209

This evolution includes major updates on the products format with respect to the current baseline (PB 03.01; PSD version 14.6).

The S2 evolution include the update of the jp2 reader to manage the source with more 4 bands.

2021-11-10 08:58 UTC, marpet reviewed
I'm fine with it. But Oana should have a look at it too before merging it

2021-11-10 09:24 UTC, oanahogoiu requested changes
The changes seem OK.
Just clean the code (remove commented lines, use debug log level instead of info)

2021-11-10 15:15 UTC, oanahogoiu commented on snap-jp2-reader/src/main/java/org/esa/snap/jp2/reader/internal/JP2TileOpImage.java
> +        String openJp2 = OpenJpegExecRetriever.getOpenJp2();//&& (this.bandData.getBandCount() == 1 || this.bandData.getBandCount() > 4)
remove commented code

2021-11-15 11:02 UTC, oanahogoiu approved these changes

2021-11-15 12:55 UTC, Florian1209 commented
It miss a function to enable openJp2 (without the option) from the the number of jpg2 band (>4).
In this case the jpg2 is necessary.

2021-11-16 07:48 UTC, Florian1209 commented
@oanahogoiu Could you have a look at the new last commit (concerning the activation of the openJp2Jna)?

2021-11-16 13:15 UTC, oanahogoiu commented
@Florian1209 It looks OK the usage of openJP2JNA when intentionnally set in the preferences and when there are more than 4 bands (regardless the preference, but openJP2 available).

2021-11-16 13:39 UTC, Florian1209 commented
@oanahogoiu  Thank you

2021-11-16 13:39 UTC, merged