Get offset and subsampling from the stored values of the GeoRaster
senbox-org/snap-engine pull request #464
Opened 2024-08-23 10:39 UTC by eomasters-repos

for ComponentGeoCoding and not from the TiePointGrid

Updated `ComponentGeoCodingPersistenceConverter` to support parsing offset and subsampling properties. Adjusted tests to initialize `ComponentGeoCoding` with offset and subsampling values.

2024-10-08 09:20 UTC, SabineEmbacher approved these changes
Looks good to me.

2024-12-16 14:12 UTC, TomBlock commented
Moin Marco, it is already out to the world - next time.

2025-02-19 08:46 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final String offsetYStr = container.getProperty(NAME_OFFSET_Y).getValueString();
If the property does not exist, a NullPointerException will be thrown here.

2025-02-19 08:46 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final String subsamplingXStr = container.getProperty(NAME_SUBSAMPLING_X).getValueString();
If the property does not exist, a NullPointerException will be thrown here.

2025-02-19 08:47 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean offsetXInvalid = offsetXStr == null;
Will never come here, if a NullPointerException is thrown above.

2025-02-19 08:48 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean offsetYInvalid = offsetYStr == null;
Will never come here, if a NullPointerException is thrown above.

2025-02-19 08:48 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean subsamplingXInvalid = subsamplingXStr == null;
Will never come here, if a NullPointerException is thrown above.

2025-02-19 08:48 UTC, SabineEmbacher commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean subsamplingYInvalid = subsamplingYStr == null;
Will never come here, if a NullPointerException is thrown above.

2025-02-19 08:58 UTC, SabineEmbacher requested changes
For backwards compatibility, it is important to be able to read in products that were written without the new properties. To do this, the code must be able to handle it somehow if the properties are not there. Or at least give a meaningful error message instead of a NullPointerException.

Tests that illustrate this backwards compatibility would be nice.

2025-02-19 08:59 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final String offsetYStr = container.getProperty(NAME_OFFSET_Y).getValueString();
Yes, same for Line 82, 83 and 84 which already existed. I only followed the existing code.

2025-02-19 08:59 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final String subsamplingXStr = container.getProperty(NAME_SUBSAMPLING_X).getValueString();
Yes, same for Line 82, 83 and 84 which already existed. I only followed the existing code.

2025-02-19 09:00 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean offsetXInvalid = offsetXStr == null;
Yes, same for Line 94, 95 and 96 which already existed. I only followed the existing code.

2025-02-19 09:00 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean offsetYInvalid = offsetYStr == null;
Yes, same for Line 94, 95 and 96 which already existed. I only followed the existing code.

2025-02-19 09:00 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean subsamplingXInvalid = subsamplingXStr == null;
Yes, same for Line 94, 95 and 96 which already existed. I only followed the existing code.

2025-02-19 09:00 UTC, eomasters-repos commented on snap-core/src/main/java/org/esa/snap/core/dataio/geocoding/ComponentGeoCodingPersistenceConverter.java
> +        final boolean subsamplingYInvalid = subsamplingYStr == null;
Yes, same for Line 94, 95 and 96 which already existed. I only followed the existing code.

2025-02-19 09:06 UTC, eomasters-repos commented
In the encoding the properties have always been used. They have only not been read. So, no need for this compatibility check. I think

2025-02-19 09:12 UTC, SabineEmbacher commented
You are right! Sorry!

2025-02-19 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/senbox-org/snap-engine?pullRequest=464) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/senbox-org/snap-engine?pullRequest=464) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: eomasters-repos<br/>:x: SabineEmbacher<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/senbox-org/snap-engine?pullRequest=464) it.</sub>

2025-02-19 14:34 UTC, SabineEmbacher commented
The code changes were added manually to the master branch.

2025-02-19 14:34 UTC, closed without merging